[preset]
name = "Only Nexus USDC bridges"
description = "Put here your description"

[functions]
# Nexus
#"nexus_bridge_usdc_arbitrum" = "Nexus Bridge USDC from Arbitrum"
#"nexus_bridge_usdc_optimism" = "Nexus Bridge USDC from Optimism"
#"nexus_bridge_usdc_base" = "Nexus Bridge USDC from Base"

# если biggest - то будет всегда бриджить из той сети, где баланс USDC больше
"nexus_bridge_usdc_biggest" = "Nexus Bridge USDC from biggest balance network"


[repeat_actions]
# здесь задаются диапазоны для рандомных повторений действий (у каждого акка будет разное количество повторений)
"nexus_bridge_usdc_biggest" = [10, 20]


[functions_params]

### Параметры первого вывода под свап USDC
[functions_params.initial_withdraw_params]
### withdraw settings
ticker = "ETH"

# тут указываем биржи для рандомного выбора (если например захочется Мекс убрать)
cex_to_random = ["Mexc", "Bitget", "Okx"]
# будет выбрана рандомная сеть, если нужна конкретная, то можно оставить одну нужную
networks_to_withdraw = ["base", "arbitrum", "optimism"]

# ЭТО ДЛЯ ПЕРВОГО БОЛЬШОГО ВЫВОДА С БИРЖИ
withdraw_eth_arbitrum_amount = [0.1, 0.2]
withdraw_eth_optimism_amount = [0.1, 0.2]
withdraw_eth_base_amount = [0.1, 0.2]


### Параметры для выводов при недостатке нативки в сетях
[functions_params.withdraw_on_min_amount_params]
# биржа для рефилла выбирается рандомно
cex_to_refill = ["Mexc", "Bitget", "Okx"]

min_eth_arbitrum_amount = 0.0005
min_eth_optimism_amount = 0.0005
min_eth_base_amount = 0.0005

# ЭТО ДЛЯ РЕФИЛЛОВ КОГДА НА ГАЗ НЕ ХВАТАЕТ
withdraw_eth_arbitrum_amount = [0.001, 0.002]
withdraw_eth_optimism_amount = [0.001, 0.002]
withdraw_eth_base_amount = [0.001, 0.002]


### Параметры для бриджей в Нексусе
[functions_params.nexus_bridge_params]
usdc_amount_to_bridge = [100, 500]

networks_to_check_balance_for_biggest = ["base", "arbitrum", "optimism"]
networks_to_bridge_to = ["base", "arbitrum", "optimism"]



### swap settings
# you will need to change only AMOUNTS
[functions_params.swap]
random_networks_to_swap = ["base", "arbitrum", "optimism"]

[functions_params.swap.base]
from_token = "native"
from_decimals = 18
to_token = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
to_decimals = 6
swap_mode = "only_to" # "to_and_from"
amount = ["20", "30"]
#amount = [1.001 , 1.003]
slippage = 0.5 # %


[functions_params.swap.optimism]
from_token = "native"
from_decimals = 18
to_token = "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
to_decimals = 6
swap_mode = "only_to"
amount = [1.001 , 1.003]
slippage = 0.5 # %

[functions_params.swap.arbitrum]
from_token = "native"
from_decimals = 18
to_token = "0xaf88d065e77c8cc2239327c5edb3a432268e5831"
to_decimals = 6
swap_mode = "only_to"
amount = [1.001 , 1.003]
slippage = 0.5 # %

# POSSIBLE SWAP MODES
# to_and_from - swaps back all available amount
# ['only_to', 'to_and_from']