[preset]
name = "Only initial swaps from ETH to USDC"
description = "Put here your description"

[functions]
# для свапов и бриджей тут указывается ИСХОДЯЩАЯ сеть

## Uniswap
#"uniswap_swap_arbitrum" = "Uniswap Swap on Arbitrum"
#"uniswap_swap_optimism" = "Uniswap Swap on Optimism"
#"uniswap_swap_base" = "Uniswap Swap on Base"
#"uniswap_swap_random" = "Uniswap Swap on random network"

## Odos
#"odos_swap_arbitrum" = "Odos Swap on Arbitrum"
"odos_swap_optimism" = "Odos Swap on Optimism"
#"odos_swap_base" = "Odos Swap on Base"
#"odos_swap_random" = "Odos Swap on Random network"

# Random swap
#"random_swap_arbitrum" = "Random DEX Swap on Arbitrum"
#"random_swap_optimism" = "Random DEX Swap on Optimism"
#"random_swap_base" = "Random DEX Swap on Base"

#### тут первый рандом это декс, второй рандом это сеть
# random сети задаются в random_networks_to_swap
"random_swap_random" = "Random DEX Swap on Random Network"

# Velodrome - только оптимизм - еще не работает, проблемы с входными данными
#"velodrome_swap_optimism" = "Swap Velodrome on Optimism"

[repeat_actions]
# здесь задаются диапазоны для рандомных повторений действий (у каждого акка будет разное количество повторений)


[functions_params]
#usdc_approve_amount = [1000, 10000]
usdc_approve_amount = "infinity"

### Параметры первого вывода под свап USDC
[functions_params.initial_withdraw_params]
### withdraw settings
ticker = "ETH" # USDC

# тут указываем биржи для рандомного выбора (если например захочется Мекс убрать)
cex_to_random = ["mexc", "bitget", "okx"]

# ЭТО ДЛЯ ПЕРВОГО БОЛЬШОГО ВЫВОДА С БИРЖИ
withdraw_eth_arbitrum_amount = [0.001, 0.002]
withdraw_eth_optimism_amount = [0.001, 0.002]
withdraw_eth_base_amount = [0.001, 0.002]

[functions_params.initial_withdraw_params.mexc]
# Сети для ПЕРВОГО вывода с Mexc
networks_to_withdraw = ["optimism"]

[functions_params.initial_withdraw_params.bitget]
# Сети для ПЕРВОГО вывода с Bitget
networks_to_withdraw = ["base", "arbitrum"]

[functions_params.initial_withdraw_params.okx]
# Сети для ПЕРВОГО вывода с Okx
networks_to_withdraw = ["base", "arbitrum"]


### Параметры для выводов при недостатке нативки в сетях
[functions_params.withdraw_on_min_amount_params]
# биржа для рефилла выбирается рандомно
cex_to_refill = ["mexc", "bitget", "okx"]

min_eth_arbitrum_amount = 0.001
min_eth_optimism_amount = 0.001
min_eth_base_amount = 0.001

# ЭТО ДЛЯ РЕФИЛЛОВ КОГДА НА ГАЗ НЕ ХВАТАЕТ
withdraw_eth_arbitrum_amount = [0.001, 0.002]
withdraw_eth_optimism_amount = [0.001, 0.002]
withdraw_eth_base_amount = [0.001, 0.002]

[functions_params.withdraw_on_min_amount_params.mexc]
# Сети для РЕФИЛЛА с Mexc
networks_to_withdraw = ["optimism"]

[functions_params.withdraw_on_min_amount_params.bitget]
# Сети для РЕФИЛЛА с Bitget
networks_to_withdraw = ["base", "arbitrum"]

[functions_params.withdraw_on_min_amount_params.okx]
# Сети для РЕФИЛЛА с Okx
networks_to_withdraw = ["base", "arbitrum"]


### Параметры для бриджей в Нексусе
[functions_params.nexus_bridge_params]
usdc_amount_to_bridge = [100, 500]

networks_to_check_balance_for_biggest = ["base", "arbitrum", "optimism"]
networks_to_bridge_to = ["base", "arbitrum", "optimism"]



### swap settings
# you will need to change only AMOUNTS
[functions_params.swap]
random_networks_to_swap = ["base", "arbitrum", "optimism"]

[functions_params.swap.base]
from_token = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
from_decimals = 6
to_token = "native"
to_decimals = 18
swap_mode = "only_to" # "to_and_from"
amount = [1 , 2]
#amount = [1.001 , 1.003]
slippage = 0.5 # %


[functions_params.swap.optimism]
from_token = "native"
from_decimals = 18
to_token = "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
to_decimals = 6
swap_mode = "only_to"
amount = ["5" , "10"]
slippage = 0.5 # %

[functions_params.swap.arbitrum]
from_token = "0xaf88d065e77c8cc2239327c5edb3a432268e5831"
from_decimals = 6
to_token = "native"
to_decimals = 18
swap_mode = "only_to"
amount = [1 , 2]
slippage = 0.5 # %

# POSSIBLE SWAP MODES
# to_and_from - swaps back all available amount
# ['only_to', 'to_and_from']